# Generated by Django 3.1.5 on 2021-03-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210319_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='students',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=0, max_digits=999)),
                ('finished', models.BooleanField(default=False)),
                ('not_answered_questions', models.ManyToManyField(blank=True, related_name='_session_not_answered_questions_+', to='quiz.Question')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.profile')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='_quiz_sessions_+', to='quiz.Session'),
        ),
    ]
