# Generated by Django 3.0.6 on 2021-03-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210321_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='session',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=999),
        ),
    ]
