# Generated by Django 3.0.6 on 2021-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='finished_sessions',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=9999999),
        ),
    ]
