# Generated by Django 3.0.6 on 2021-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiz_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quizzies',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='finished_sessions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='public',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='views',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=99999),
        ),
    ]
