# Generated by Django 3.0.6 on 2021-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210325_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='finished_sessions',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=99999),
        ),
        migrations.AddField(
            model_name='quiz',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
