# Generated by Django 3.1.5 on 2021-03-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_profile_quizzies'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.profile')),
                ('students', models.ManyToManyField(blank=True, related_name='_quizclass_students_+', to='quiz.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('sessions', models.ManyToManyField(blank=True, related_name='_classsession_sessions_+', to='quiz.Session')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='_profile_classes_+', to='quiz.QuizClass'),
        ),
    ]
