# Generated by Django 3.1.5 on 2021-03-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20210325_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='quiz_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizclass'),
        ),
        migrations.AddField(
            model_name='profile',
            name='classes_owner',
            field=models.ManyToManyField(blank=True, related_name='_profile_classes_owner_+', to='quiz.QuizClass'),
        ),
        migrations.AddField(
            model_name='quizclass',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='_quizclass_sessions_+', to='quiz.ClassSession'),
        ),
    ]
