# Generated by Django 3.0.6 on 2021-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_auto_20210325_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizclass',
            name='name',
            field=models.CharField(default='ASD', max_length=200),
            preserve_default=False,
        ),
    ]
