# Generated by Django 4.0.4 on 2022-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_quizclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.session'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.quizclass'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='classes_owner',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.quizclass'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quizzies',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.answer'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.session'),
        ),
        migrations.AlterField(
            model_name='quizclass',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.classsession'),
        ),
        migrations.AlterField(
            model_name='quizclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.profile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='not_answered_questions',
            field=models.ManyToManyField(blank=True, related_name='+', to='quiz.question'),
        ),
    ]
